### ISSUE TITLE
Transform automatically to uppercase

### ISSUE THREAD

**Issue by carles9000** [igorescobar/jQuery-Mask-Plugin#359]
Hi,

Do you know if is posible to write in lowercase (standard writing) and transform it automatically to uppercase ?

I'm looking for a plug-in that solve me it. I don't want that user press shift key before write.

Thanks in advance for your help.
Carlos.

**Comment by mscarchilli** [comment]
CSS text-transform?

```css
.class {
  text-transform: uppercase;
}
```
